name: ai-pipeline
on: [push]

jobs:
  plan:
    runs-on: windows-latest
    env:
      CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @anthropic-ai/claude-code
      - run: claude auth login --api-key ${{ secrets.CLAUDE_API_KEY }}
      - run: claude /orchestrator plan